{{- if .Values.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zoochacha-cert
  namespace: {{ .Values.global.namespaces.nginx }}
spec:
  secretName: nginx-tls
  issuerRef:
    name: {{ .Values.tls.clusterIssuer.name }}
    kind: ClusterIssuer
  dnsNames:
  - "{{ .Values.global.domain }}"
  - "www.{{ .Values.global.domain }}"
{{- end }} 