apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.tls.clusterIssuer.name }}
spec:
  acme:
    email: {{ .Values.tls.clusterIssuer.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: acm-account-key
    solvers:
    - dns01:
        route53:
          region: {{ .Values.aws.region }}
          accessKeyID: {{ .Values.aws.accessKeyID }}
          secretAccessKeySecretRef:
            name: route53-credentials
            key: secret-access-key 