{{- if .Values.tls.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-route53
  namespace: {{ .Values.global.namespaces.cert_manager }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.aws.roleArn }}
{{- end }} 