{{- range .Values.namespaces }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .name }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-100"
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
    {{- range $key, $value := .labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
{{- end }} 