{{- if .Values.argocd.enabled }}
{{- if .Values.argocd.application.enabled }}
---
# 관리자 애플리케이션
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: admin-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/part-of: zoochacha
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  project: default
  source:
    repoURL: https://github.com/Goorm-Cloud/manifast-admin.git
    targetRevision: {{ .Values.argocd.application.source.targetRevision }}
    path: .
  destination:
    server: {{ .Values.argocd.application.destination.server }}
    namespace: zoochacha
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
# 지도 서비스 애플리케이션
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: map-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/part-of: zoochacha
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  project: default
  source:
    repoURL: https://github.com/Goorm-Cloud/manifast-map.git
    targetRevision: {{ .Values.argocd.application.source.targetRevision }}
    path: .
  destination:
    server: {{ .Values.argocd.application.destination.server }}
    namespace: zoochacha
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
# 예약 서비스 애플리케이션
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reservation-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/part-of: zoochacha
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  project: default
  source:
    repoURL: https://github.com/Goorm-Cloud/manifast-reservation.git
    targetRevision: {{ .Values.argocd.application.source.targetRevision }}
    path: .
  destination:
    server: {{ .Values.argocd.application.destination.server }}
    namespace: zoochacha
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
# 예약 상세 서비스 애플리케이션
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reservation-detail-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/part-of: zoochacha
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  project: default
  source:
    repoURL: https://github.com/Goorm-Cloud/manifast-rds.git
    targetRevision: {{ .Values.argocd.application.source.targetRevision }}
    path: .
  destination:
    server: {{ .Values.argocd.application.destination.server }}
    namespace: zoochacha
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
{{- end }} 