{{- if .Values.database.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: {{ .Values.global.namespaces.db }}
data:
  DB_HOST: {{ .Values.database.host | quote }}
  DB_PORT: {{ .Values.database.port | quote }}
  DB_NAME: {{ .Values.database.database | quote }}
  DB_TYPE: {{ .Values.database.type | quote }}
{{- end }} 