{{- if .Values.rbac.create }}
# Service Account 생성
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.serviceAccountName }}
  namespace: {{ .Values.rbac.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-200"
    "helm.sh/hook-delete-policy": hook-succeeded
---
# 클러스터 롤 생성 - 관리자 권한 부여
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.rbac.serviceAccountName }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-190"
    "helm.sh/hook-delete-policy": hook-succeeded
rules:
# 네임스페이스 관리 권한
- apiGroups: [""]
  resources: ["namespaces", "serviceaccounts"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# 클러스터 롤과 롤 바인딩 관리 권한
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles", "clusterrolebindings"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# 인증서 및 인증 관련 리소스 관리 권한
- apiGroups: ["cert-manager.io"]
  resources: ["certificates", "issuers", "clusterissuers", "challenges", "orders"]
  verbs: ["get", "list", "create", "delete", "watch"]
# 배포, 서비스, Pod 등 기본 리소스 관리 권한
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets", "events", "serviceaccounts", "persistentvolumeclaims"]
  verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
# 배포, StatefulSet 관리 권한
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "replicasets"]
  verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
# Job 관리 권한
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
# 네트워크 정책 관리 권한
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses", "networkpolicies"]
  verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
# CRD 확인 권한
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# ArgoCD 애플리케이션 관리 권한
- apiGroups: ["argoproj.io"]
  resources: ["applications", "applicationsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
# 클러스터 롤 바인딩 생성
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.rbac.serviceAccountName }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-180"
    "helm.sh/hook-delete-policy": hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.rbac.serviceAccountName }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.rbac.serviceAccountName }}
  namespace: {{ .Values.rbac.namespace }}
{{- end }} 